services:
  fastapi:
    build: .
    ports:
      - "9000:9000"  # 👈 Add this to expose it outside

  nginx:
    image: nginx:alpine
    ports:
      - "8084:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
